### ISSUE TITLE
Hawaii doesn't appear to build agaisnt NetworkManager 1.2

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#223] opened 2016-05-10 01:30 UTC
For some reason I am still getting these errors trying to comple Hawaii-Shell

[ 97%] Building CXX object compositor/CMakeFiles/hawaii.dir/sessionmanager/screensaver/screensaveradaptor.cpp.o
[ 98%] Building CXX object compositor/CMakeFiles/hawaii.dir/qrc_hawaii.cpp.o
[ 98%] Linking CXX shared library libnmplugin.so
[ 99%] Building CXX object compositor/CMakeFiles/hawaii.dir/hawaii_automoc.cpp.o
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::addWimaxNsp(QSharedPointer<NetworkManager::WimaxNsp> const&, QSharedPointer<NetworkManager::WimaxDevice> const&)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:481: undefined reference to `NetworkManager::WimaxNsp::name() const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:482: undefined reference to `NetworkManager::WimaxNsp::signalQuality() const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:483: undefined reference to `NetworkManager::WimaxNsp::uni() const'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::updateFromWimaxNsp(NetworkModelItem*, QSharedPointer<NetworkManager::WimaxNsp> const&)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:1101: undefined reference to `NetworkManager::WimaxNsp::signalQuality() const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:1102: undefined reference to `NetworkManager::WimaxNsp::uni() const'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkManager::WimaxNsp* qobject_cast<NetworkManager::WimaxNsp*>(QObject*)':
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxNsp::staticMetaObject'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::wimaxNspSignalChanged(unsigned int)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:1001: undefined reference to `NetworkManager::WimaxNsp::name() const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:1002: undefined reference to `NetworkManager::WimaxNsp::uni() const'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkManager::WimaxDevice* qobject_cast<NetworkManager::WimaxDevice*>(QObject*)':
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxDevice::staticMetaObject'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::wimaxNspAppeared(QString const&)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:962: undefined reference to `NetworkManager::WimaxDevice::findNsp(QString const&) const'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkManager::WimaxDevice* qobject_cast<NetworkManager::WimaxDevice*>(QObject*)':
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxDevice::staticMetaObject'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::availableConnectionDisappeared(QString const&)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:705: undefined reference to `NetworkManager::WimaxDevice::findNsp(QString const&) const'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkManager::WimaxDevice* qobject_cast<NetworkManager::WimaxDevice*>(QObject*)':
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxDevice::staticMetaObject'
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxDevice::staticMetaObject'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::addAvailableConnection(QString const&, QSharedPointer<NetworkManager::Device> const&)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:388: undefined reference to `NetworkManager::WimaxDevice::findNsp(QString const&) const'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkManager::WimaxDevice* qobject_cast<NetworkManager::WimaxDevice*>(QObject*)':
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxDevice::staticMetaObject'
CMakeFiles/nmplugin.dir/networkmodel.cpp.o: In function `NetworkModel::addDevice(QSharedPointer<NetworkManager::Device> const&)':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:457: undefined reference to `NetworkManager::WimaxDevice::nsps() const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodel.cpp:458: undefined reference to `NetworkManager::WimaxDevice::findNsp(QString const&) const'
CMakeFiles/nmplugin.dir/networkmodelitem.cpp.o: In function `NetworkManager::WimaxDevice* qobject_cast<NetworkManager::WimaxDevice*>(QObject*)':
/opt/include/QtCore/qobject.h:516: undefined reference to `NetworkManager::WimaxDevice::staticMetaObject'
CMakeFiles/nmplugin.dir/networkmodelitem.cpp.o: In function `NetworkModelItem::updateDetails()':
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodelitem.cpp:564: undefined reference to `NetworkManager::WimaxDevice::findNsp(QString const&) const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodelitem.cpp:570: undefined reference to `NetworkManager::WimaxDevice::bsid() const'
/srcbuild/hawaii-shell/declarative/networkmanager/networkmodelitem.cpp:571: undefined reference to `NetworkManager::WimaxDevice::hardwareAddress() const'
collect2: error: ld returned 1 exit status
declarative/networkmanager/CMakeFiles/nmplugin.dir/build.make:432: recipe for target 'declarative/networkmanager/libnmplugin.so' failed
make[2]: *** [declarative/networkmanager/libnmplugin.so] Error 1
CMakeFiles/Makefile2:1000: recipe for target 'declarative/networkmanager/CMakeFiles/nmplugin.dir/all' failed
make[1]: *** [declarative/networkmanager/CMakeFiles/nmplugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable hawaii
[100%] Built target hawaii
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 163 seconds

**Comment by plfiorini** [comment] 2016-05-10 05:24
After https://github.com/hawaii-desktop/hawaii-shell/commit/4cd524e9e3fd8ceca19b8b9f9f274c7eef9eaf4f it was building (tested on Fedora 24 and Arch VMs) but the errors here seem different. Did you build NM 1.2 with particular configure arguments?

**Comment by n3rdopolis** [comment] 2016-05-10 07:46
It's actually NetworkManager from Debian Testing

**Comment by h4nn35** [comment] 2016-05-10 11:52
I also tried to build hawaii for the first time on my arch linux and ran into the same troubles -> the networkmanager 1.2 has dropped the wimax support:
http://www.phoronix.com/scan.php?page=news_item&px=networkmanager-drops-wimax

networkmanager-qt now has defines to check for the version:
#if !NM_CHECK_VERSION(1, 2, 0)

**Comment by plfiorini** [comment] 2016-05-10 12:04
i've done a number of wimax related changes and bulti fine on both fedora 24 and arch, probably there is something left to put inside #ifdef but that sounds weird. @n3rdopolis are you using master?

**Comment by n3rdopolis** [comment] 2016-05-10 12:08
Hi. I am using master

**Comment by plfiorini** [comment] 2016-05-10 12:11
ok then i will grep for more wimax that might have been missed

**Comment by h4nn35** [comment] 2016-05-10 13:47
Sorry for the noise. I switched to master and had still compilation errors which were caused by networkmodel.cpp and networkitem.cpp. After commenting everything related to wimax in these two files I was able to compile.

**Comment by plfiorini** [comment] 2016-05-13 19:57
Closing because fix was merged, but can be reopened if there's still problems.

**Closed by plfiorini** 2016-05-13 19:57 UTC
