### ISSUE TITLE
load glyph failed err=24

### ISSUE THREAD

**Issue by fleixi** [hawaii-desktop/hawaii-shell#184] opened 2015-05-05 17:34 UTC
I getting many glyph errors an is only showing the background without panels. But if i try to click something (there is no mouse too) i get some error like "qml: Failed to run: org.kde.konsole" so i think the panel is just invisble.

Erroroutput:
http://pastebin.com/xFk4tiqW

On papyros there is the same error so maybe it is a grennisland error.

https://github.com/papyros/papyros-shell/issues/38

The person in this issues is using the same hardware (odroid-xu).

Tested with qt5.4.3 and qt5.5
##

**Comment by plfiorini** [comment] 2015-05-05 17:37
Don't think Papyros was using green island back then so maybe this is Qt related.

**Comment by plfiorini** [comment] 2015-05-05 17:38
The same guy indeed reproduced the same issue with Hawaii and posted a video.

https://www.youtube.com/watch?v=IYP0k0lq6cc

Guess it's time for me to buy this card :)

**Comment by plfiorini** [comment] 2015-05-05 17:54
I noticed the available geometry is weird, see pastebin at line 167:
qml: Available geometry for  is: QRect(0, 0, 1920, 1610613814)

The load glyph failed error is about fonts: https://bugreports.qt.io/browse/QTBUG-12196

**Comment by plfiorini** [comment] 2015-05-05 18:10
Perhaps I have a clue:
* The panel background is transparent and becomes a solid color when a window is maximized, hence it's transparent when you start a Hawaii session
* The default launcher configuration shows two applications: Konsole and Hawaii System Preferences.
* Such applications are probably not installed, this explains "qml: Failed to run: org.kde.konsole"
* You probably don't see the "Menu" label on the bottom left corner because of all the glyph failed errors indicate something is wrong with the fonts

@fleixi Could you please try clicking where the "Menu" label is supposed to be and see if the menu shows up?

Just to be sure: do you see the blue default wallpaper (https://github.com/hawaii-desktop/hawaii-wallpapers/blob/master/backgrounds/Also_Calm.png)?

**Comment by fleixi** [comment] 2015-05-05 18:29
I will try it tomorrow, no time left today :-D

Yes I'm seeing the background, but there is a gray overlay just like in the video.

It is hard to find the menu without a cursor but it should be in the near of the console launcher right?!

Sadly the missing cursor doesn't fit in your analytic very well.

Am 5. Mai 2015 20:10:23 MESZ, schrieb Pier Luigi Fiorini <notifications@github.com>:

**Comment by fleixi** [comment] 2015-05-06 17:29
This is the new output:

http://pastebin.com/Lhd3pidR

I have tried to move the cusore (with is invisible) an clicked many times. The weared part is that i have moved the mouse on my table 1cm and more and getting the same output about a missing programm like konsole.

Then there is a error about not finding "wind" and also about "hawaii-system-preferences" but both are installed. So i think there still some import problems too.

The hole time clicking and moving the mouse no window or something else is shown on the screen.

**Comment by plfiorini** [comment] 2015-05-22 22:55
cursor might be fixed now: https://github.com/hawaii-desktop/hawaii-shell/commit/dfa7962d75663d1d0930d590636a7518da35cd41
also removed a couple of env vars that depends on the hw, those might have been wrong for your config: https://github.com/hawaii-desktop/hawaii-shell/commit/3d19088d12cd6bfa066211be8b43680a65872949

**Comment by fleixi** [comment] 2015-05-24 11:03
Saddly no real changes:

http://pastebin.com/hyFfVRiW

btw i have change the path of qt5.5 and hawaii to /opt/qt5.5 to avoiding left over configerrors.

The cursor isnt there, no panel and the same errors but take a look at my pastebin, maybe something have changed there.

**Comment by plfiorini** [comment] 2015-05-24 12:25
Qt 5.5 has support for XU with eglfs (Mali GPU), not sure if you built it.
I'm curious if that changes anything.

**Comment by fleixi** [comment] 2015-05-24 12:30
The xu isnt  using a mali GPU. It is using a powervr. The xu3 is using a mali GPU.

Thats the big problem  with the xu.

Am 24. Mai 2015 14:25:35 MESZ, schrieb Pier Luigi Fiorini <notifications@github.com>:
>Qt 5.5 has support for XU with eglfs (Mali GPU), not sure if you built
>it.
>I'm curious if that changes anything.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hawaii-desktop/hawaii-shell/issues/184#issuecomment-105009807

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by plfiorini** [comment] 2015-05-25 14:55
Right, nvm... Qt 5.4 removed the page flipper from Qt itself, I wonder if this is reason.
Could you please summarize what upstream stuff did you build to get hybris on the board and where do I find it? That would help me build packages for that stuff and tamper with hybris myself on one of my boards.

Also, is this GPU similar to OMAP4 on Pandaboard? Because that in theory work with KMS and Qt 5.5 now has finally eglfs_kms

**Comment by fleixi** [comment] 2015-05-25 20:54
Im not so into the graphicstuff on embedded pcs so i dont know if the GPUs are simliar, the  Odroid-Xu is using the SGX544MP3 and the Pandaboard is using the SGX540. The only think i know is that the developer and the community from the XU wasnt able to write an working grapficdriver. The only way so far known are using the androiddriver. But the board isnt in active developing anymore so maybe there is a better way now.

technical data XU = http://www.hardkernel.com/main/products/prdt_info.php?g_code=G137510300620&tab_idx=1

Im using this sources: 
(http://forum.odroid.com/viewtopic.php?f=62&t=2176#p50530)

odroid-xu-kernel 3.4 with android-binder compiled (Should be the same on all other kernels too)

wayland = git://anongit.freedesktop.org/wayland/wayland (no patches)

libhybris = https://github.com/libhybris/libhybris.git (no patches, using the android 4.4.2 headers for the xu)

till here following the forumpost

qt-base = https://gitorious.org/qt/qtbase.git (branch 5.5 ./configure --opengl es2, no patches)

qt-wayland = your modified qtwayland posted in greenisland (branch 5.5)

qpa-hwcomposer-plugin = your qt5-qpa-hwcomposer-plugin-5.4.1 (https://build.merproject.org/package/show/home:plfiorini:maui:devel:hw:lge:hammerhead/qt5-qpa-hwcomposer-plugin, no patches, this version dont need ScreenPageFlipper but it could easily reimplemented in qt5.5 by reverse this commit = https://qt.gitorious.org/qt/qtbase/commit/97cd20b2a02998e610d97e1907c23ad420f58502)

all dependences for hawaii from  the official git-repos without patches

I dont using exotic stuff. Only important is to compile qt-base with --opengl es2. without qt-wayland is trying to use the normal opengl without success.

**Comment by plfiorini** [comment] 2016-02-06 20:19
Might be related to this problem: https://github.com/greenisland/greenisland/issues/180
Drivers reporting a 0x0 physical size result in broken font rendering, failure loading icons from the icon theme and possibily a number of other issues including broken or invisible panel.

**Comment by plfiorini** [comment] 2016-02-06 20:23
The greenisland QPA now has a workaround but it only support kms, wayland and xcb.
I haven't added hwcomposer support yet so when using qt5-qpa-hwcompositor the following env vars *might* do the trick:

``sh
export QT_QPA_EGLFS_PHYSICAL_WIDTH=487
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=274
``

This is roughly the size in millimiters of a 22" monitor.

**Closed** 2016-11-11 07:29 UTC

**Comment by SwordofMorning** [comment] 2025-04-10 01:41
Meet the same issue:

```
load glyph failed err=24 face=0x81fe0, glyph=28
load glyph failed err=24 face=0x81fe0, glyph=27
load glyph failed err=24 face=0x81fe0, glyph=24
load glyph failed err=24 face=0x81fe0, glyph=73
load glyph failed err=24 face=0x81fe0, glyph=74
load glyph failed err=24 face=0x81fe0, glyph=20
load glyph failed err=24 face=0x81fe0, glyph=81
load glyph failed err=24 face=0x81fe0, glyph=82
load glyph failed err=24 face=0x81fe0, glyph=3
load glyph failed err=24 face=0x81fe0, glyph=79
load glyph failed err=24 face=0x81fe0, glyph=68
load glyph failed err=24 face=0x81fe0, glyph=92
load glyph failed err=24 face=0x81fe0, glyph=88
load glyph failed err=24 face=0x81fe0, glyph=87
load glyph failed err=24 face=0x81fe0, glyph=75
load glyph failed err=24 face=0x81fe0, glyph=86
```

and 

```
export QT_QPA_EGLFS_PHYSICAL_WIDTH=487
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=274
```

it is works.
